export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const CHECK_USER_LOGGED_IN = 'CHECK_USER_LOGGED_IN';
export const USER_LOGGED_IN_DETAILS = 'USER_LOGGED_IN_DETAILS';
export const CUSTOMER_REQUEST_ACTIVE_TAB = ' CUSTOMER_REQUEST_ACTIVE_TAB';
export const FEEDBACK_ACTIVE_TAB = "FEEDBACK_ACTIVE_TAB";
export const USER_LOG_OUT = "USER_LOG_OUT";
export const USER_LOGIN_IN = "USER_LOGIN_IN";